services:
  backend:
    build: .
    command: yarn start
    ports: 
      - 8080:8080
    environment:
      - DATABASE_HOST=mongodb
  mongodb:
    image: mongo:latest
    ports: 
      - 8181:27017
    volumes: 
      - mongodb:/data/db
volumes:
  mongodb:
    driver: local