services:
  server:
    env_file: [.env]
    environment: { DATABASE_HOST: mongodb }
    build: .
    command: yarn start
    ports: [8080:8080]
    depends_on: [mongodb]
  mongodb:
    image: mongo:latest
    ports: [27018:27017]
    volumes: [mongodb:/data/db]
volumes: {
  mongodb: {
    driver: local
  }
}